server:
  port: 8080

spring:
  application:
    name: API-GATEWAY
  config:
    import: "optional:configserver:http://localhost:8098/"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # Enable service discovery
          lowerCaseServiceId: true
      routes:
        - id: student-service
          uri: lb://STUDENT-SERVICE
          predicates:
            - Path=/api/students/**
        - id: teacher-service
          uri: lb://TEACHER-SERVICE
          predicates:
            - Path=/api/teachers/**
        - id: parent-service
          uri: lb://PARENT-SERVICE
          predicates:
            - Path=/api/parents/**
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/payments/**
        - id: transportation-service
          uri: lb://TRANSPORTATION-SERVICE
          predicates:
            - Path=/api/transportation/**
        - id: attendance-service
          uri: lb://ATTENDANCE-SERVICE
          predicates:
            - Path=/api/attendance/**
        - id: general-settings-service
          uri: lb://GENERAL-SETTINGS-SERVICE
          predicates:
            - Path=/api/general-settings/**
        - id: holiday-service
          uri: lb://HOLIDAY-SERVICE
          predicates:
            - Path=/api/holidays/**
        - id: hall-service
          uri: lb://HALL-SERVICE
          predicates:
            - Path=/api/halls/**
        - id: notice-service
          uri: lb://NOTICE-SERVICE
          predicates:
            - Path=/api/notices/**
        - id: migration-service
          uri: lb://MIGRATION-SERVICE
          predicates:
            - Path=/api/migration/**
        - id: grade-service
          uri: lb://GRADE-SERVICE
          predicates:
            - Path=/api/grades/**
        - id: mark-service
          uri: lb://MARK-SERVICE
          predicates:
            - Path=/api/marks/**


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true

info:
  app:
    name: "APIGateway"
    description: "School Management Service Gateway Server Application"
    version: "1.0.0"

logging:
  level:
    com:
      azka:
        schoolmanagementsystem: DEBUG

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: "http://localhost:8099/eureka/"